topp_tracker:
  from_odom: True
  sampling_frequency: 50
  n_gridpoints: 100
  request_permission: False

  constraints:

    velocity:
      x: 2
      y: 2
      z: 2
      yaw: 1.5

    acceleration:
      x: 1.75
      y: 1.75
      z: 1.75
      yaw: 1.5
